// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: nominatim/v1/nominatim.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 基本地理坐标
type Point struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 纬度（范围：-90 到 90）
	Lat float64 `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	// 经度（范围：-180 到 180）
	Lon           float64 `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_nominatim_v1_nominatim_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_nominatim_v1_nominatim_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_nominatim_v1_nominatim_proto_rawDescGZIP(), []int{0}
}

func (x *Point) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Point) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

// 外接矩形（左、上、右、下）
type ViewBox struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 左（最小经度）
	Left float64 `protobuf:"fixed64,1,opt,name=left,proto3" json:"left,omitempty"`
	// 上（最大纬度）
	Top float64 `protobuf:"fixed64,2,opt,name=top,proto3" json:"top,omitempty"`
	// 右（最大经度）
	Right float64 `protobuf:"fixed64,3,opt,name=right,proto3" json:"right,omitempty"`
	// 下（最小纬度）
	Bottom        float64 `protobuf:"fixed64,4,opt,name=bottom,proto3" json:"bottom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewBox) Reset() {
	*x = ViewBox{}
	mi := &file_nominatim_v1_nominatim_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewBox) ProtoMessage() {}

func (x *ViewBox) ProtoReflect() protoreflect.Message {
	mi := &file_nominatim_v1_nominatim_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewBox.ProtoReflect.Descriptor instead.
func (*ViewBox) Descriptor() ([]byte, []int) {
	return file_nominatim_v1_nominatim_proto_rawDescGZIP(), []int{1}
}

func (x *ViewBox) GetLeft() float64 {
	if x != nil {
		return x.Left
	}
	return 0
}

func (x *ViewBox) GetTop() float64 {
	if x != nil {
		return x.Top
	}
	return 0
}

func (x *ViewBox) GetRight() float64 {
	if x != nil {
		return x.Right
	}
	return 0
}

func (x *ViewBox) GetBottom() float64 {
	if x != nil {
		return x.Bottom
	}
	return 0
}

// 边界框（南、北、西、东）
type BoundingBox struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 南（最小纬度）
	South float64 `protobuf:"fixed64,1,opt,name=south,proto3" json:"south,omitempty"`
	// 北（最大纬度）
	North float64 `protobuf:"fixed64,2,opt,name=north,proto3" json:"north,omitempty"`
	// 西（最小经度）
	West float64 `protobuf:"fixed64,3,opt,name=west,proto3" json:"west,omitempty"`
	// 东（最大经度）
	East          float64 `protobuf:"fixed64,4,opt,name=east,proto3" json:"east,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	mi := &file_nominatim_v1_nominatim_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_nominatim_v1_nominatim_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundingBox.ProtoReflect.Descriptor instead.
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return file_nominatim_v1_nominatim_proto_rawDescGZIP(), []int{2}
}

func (x *BoundingBox) GetSouth() float64 {
	if x != nil {
		return x.South
	}
	return 0
}

func (x *BoundingBox) GetNorth() float64 {
	if x != nil {
		return x.North
	}
	return 0
}

func (x *BoundingBox) GetWest() float64 {
	if x != nil {
		return x.West
	}
	return 0
}

func (x *BoundingBox) GetEast() float64 {
	if x != nil {
		return x.East
	}
	return 0
}

// 本地化语言优先级
type Locales struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 语言代码列表（按优先级排列），例如：zh、en
	Codes         []string `protobuf:"bytes,1,rep,name=codes,proto3" json:"codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Locales) Reset() {
	*x = Locales{}
	mi := &file_nominatim_v1_nominatim_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Locales) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Locales) ProtoMessage() {}

func (x *Locales) ProtoReflect() protoreflect.Message {
	mi := &file_nominatim_v1_nominatim_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Locales.ProtoReflect.Descriptor instead.
func (*Locales) Descriptor() ([]byte, []int) {
	return file_nominatim_v1_nominatim_proto_rawDescGZIP(), []int{3}
}

func (x *Locales) GetCodes() []string {
	if x != nil {
		return x.Codes
	}
	return nil
}

// 地址行组件（对齐 Nominatim address）
type AddressRow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 地址组件的人类可读名称
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 地址组件类型（country/state/city/road/house_number 等）
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// OSM admin_level 或类似等级，未知时可为 0
	AdminLevel uint32 `protobuf:"varint,3,opt,name=admin_level,json=adminLevel,proto3" json:"admin_level,omitempty"`
	// 排序/重要性等级（越小越上层）
	Rank          uint32 `protobuf:"varint,4,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressRow) Reset() {
	*x = AddressRow{}
	mi := &file_nominatim_v1_nominatim_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressRow) ProtoMessage() {}

func (x *AddressRow) ProtoReflect() protoreflect.Message {
	mi := &file_nominatim_v1_nominatim_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressRow.ProtoReflect.Descriptor instead.
func (*AddressRow) Descriptor() ([]byte, []int) {
	return file_nominatim_v1_nominatim_proto_rawDescGZIP(), []int{4}
}

func (x *AddressRow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddressRow) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AddressRow) GetAdminLevel() uint32 {
	if x != nil {
		return x.AdminLevel
	}
	return 0
}

func (x *AddressRow) GetRank() uint32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

// 搜索结果（尽量对齐 Nominatim 输出）
type Place struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 内部 place_id（Nominatim 主键）
	PlaceId int64 `protobuf:"varint,1,opt,name=place_id,json=placeId,proto3" json:"place_id,omitempty"`
	// 许可证说明（若有）
	Licence string `protobuf:"bytes,2,opt,name=licence,proto3" json:"licence,omitempty"`
	// OSM 对象 ID（字符串形式）
	OsmId string `protobuf:"bytes,3,opt,name=osm_id,json=osmId,proto3" json:"osm_id,omitempty"`
	// OSM 对象类型（node/way/relation）
	OsmType string `protobuf:"bytes,4,opt,name=osm_type,json=osmType,proto3" json:"osm_type,omitempty"`
	// OSM 类别（class：amenity/place/boundary 等）
	Category string `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	// OSM 类型详细值（type：restaurant/city/administrative 等）
	Type string `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	// 结果的重要性分值（importance）
	Importance float64 `protobuf:"fixed64,7,opt,name=importance,proto3" json:"importance,omitempty"`
	// 结果的展示名称（本地化后的人类可读标签）
	DisplayName string `protobuf:"bytes,8,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// 结果的几何中心点（质心）
	Centroid *Point `protobuf:"bytes,9,opt,name=centroid,proto3" json:"centroid,omitempty"`
	// 边界框（south, north, west, east）
	Boundingbox *BoundingBox `protobuf:"bytes,10,opt,name=boundingbox,proto3" json:"boundingbox,omitempty"`
	// 图标 URL（若对象具备）
	Icon string `protobuf:"bytes,11,opt,name=icon,proto3" json:"icon,omitempty"`
	// 额外标签（extratags）
	Extratags map[string]string `protobuf:"bytes,12,rep,name=extratags,proto3" json:"extratags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 名称细节（namedetails）
	Namedetails map[string]string `protobuf:"bytes,13,rep,name=namedetails,proto3" json:"namedetails,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 地址行明细（用于 addressdetails=true）
	AddressRows []*AddressRow `protobuf:"bytes,14,rep,name=address_rows,json=addressRows,proto3" json:"address_rows,omitempty"`
	// 面要素的 GeoJSON（当 polygon_geojson=true 时返回）
	PolygonGeojson string `protobuf:"bytes,15,opt,name=polygon_geojson,json=polygonGeojson,proto3" json:"polygon_geojson,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Place) Reset() {
	*x = Place{}
	mi := &file_nominatim_v1_nominatim_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Place) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Place) ProtoMessage() {}

func (x *Place) ProtoReflect() protoreflect.Message {
	mi := &file_nominatim_v1_nominatim_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Place.ProtoReflect.Descriptor instead.
func (*Place) Descriptor() ([]byte, []int) {
	return file_nominatim_v1_nominatim_proto_rawDescGZIP(), []int{5}
}

func (x *Place) GetPlaceId() int64 {
	if x != nil {
		return x.PlaceId
	}
	return 0
}

func (x *Place) GetLicence() string {
	if x != nil {
		return x.Licence
	}
	return ""
}

func (x *Place) GetOsmId() string {
	if x != nil {
		return x.OsmId
	}
	return ""
}

func (x *Place) GetOsmType() string {
	if x != nil {
		return x.OsmType
	}
	return ""
}

func (x *Place) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Place) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Place) GetImportance() float64 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *Place) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Place) GetCentroid() *Point {
	if x != nil {
		return x.Centroid
	}
	return nil
}

func (x *Place) GetBoundingbox() *BoundingBox {
	if x != nil {
		return x.Boundingbox
	}
	return nil
}

func (x *Place) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Place) GetExtratags() map[string]string {
	if x != nil {
		return x.Extratags
	}
	return nil
}

func (x *Place) GetNamedetails() map[string]string {
	if x != nil {
		return x.Namedetails
	}
	return nil
}

func (x *Place) GetAddressRows() []*AddressRow {
	if x != nil {
		return x.AddressRows
	}
	return nil
}

func (x *Place) GetPolygonGeojson() string {
	if x != nil {
		return x.PolygonGeojson
	}
	return ""
}

// /search 请求（尽量对齐参数集）
type SearchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 查询关键字（名称/地址/类型）
	Q string `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	// 限制国家代码（与 Python 参数名兼容），多个以逗号分隔
	Countrycodes string `protobuf:"bytes,2,opt,name=countrycodes,proto3" json:"countrycodes,omitempty"`
	// 返回数量上限（1-50）
	Limit uint32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// 分页偏移（>=0）
	Offset uint32 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	// 是否返回地址行明细（与 Python 参数名兼容）
	Addressdetails bool `protobuf:"varint,5,opt,name=addressdetails,proto3" json:"addressdetails,omitempty"`
	// 接受的语言（如："zh,en"），用于本地化显示
	AcceptLanguage string `protobuf:"bytes,6,opt,name=accept_language,json=acceptLanguage,proto3" json:"accept_language,omitempty"`
	// 本地化语言优先级（服务内部使用）
	Locales *Locales `protobuf:"bytes,7,opt,name=locales,proto3" json:"locales,omitempty"`
	// 搜索类型过滤（class/type 组合，若支持）
	Featuretype string `protobuf:"bytes,8,opt,name=featuretype,proto3" json:"featuretype,omitempty"`
	// 去重（按相同对象、位置）
	Dedupe bool `protobuf:"varint,9,opt,name=dedupe,proto3" json:"dedupe,omitempty"`
	// 视窗范围（viewbox）
	Viewbox *ViewBox `protobuf:"bytes,10,opt,name=viewbox,proto3" json:"viewbox,omitempty"`
	// 是否限制在视窗内（bounded=1）
	Bounded bool `protobuf:"varint,11,opt,name=bounded,proto3" json:"bounded,omitempty"`
	// 是否返回多边形（GeoJSON）
	PolygonGeojson bool `protobuf:"varint,12,opt,name=polygon_geojson,json=polygonGeojson,proto3" json:"polygon_geojson,omitempty"`
	// 多边形简化阈值（0-1，越大简化越多）
	PolygonThreshold float64 `protobuf:"fixed64,13,opt,name=polygon_threshold,json=polygonThreshold,proto3" json:"polygon_threshold,omitempty"`
	// 是否返回 extratags
	Extratags bool `protobuf:"varint,14,opt,name=extratags,proto3" json:"extratags,omitempty"`
	// 是否返回 namedetails
	Namedetails   bool `protobuf:"varint,15,opt,name=namedetails,proto3" json:"namedetails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_nominatim_v1_nominatim_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nominatim_v1_nominatim_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_nominatim_v1_nominatim_proto_rawDescGZIP(), []int{6}
}

func (x *SearchRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *SearchRequest) GetCountrycodes() string {
	if x != nil {
		return x.Countrycodes
	}
	return ""
}

func (x *SearchRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SearchRequest) GetAddressdetails() bool {
	if x != nil {
		return x.Addressdetails
	}
	return false
}

func (x *SearchRequest) GetAcceptLanguage() string {
	if x != nil {
		return x.AcceptLanguage
	}
	return ""
}

func (x *SearchRequest) GetLocales() *Locales {
	if x != nil {
		return x.Locales
	}
	return nil
}

func (x *SearchRequest) GetFeaturetype() string {
	if x != nil {
		return x.Featuretype
	}
	return ""
}

func (x *SearchRequest) GetDedupe() bool {
	if x != nil {
		return x.Dedupe
	}
	return false
}

func (x *SearchRequest) GetViewbox() *ViewBox {
	if x != nil {
		return x.Viewbox
	}
	return nil
}

func (x *SearchRequest) GetBounded() bool {
	if x != nil {
		return x.Bounded
	}
	return false
}

func (x *SearchRequest) GetPolygonGeojson() bool {
	if x != nil {
		return x.PolygonGeojson
	}
	return false
}

func (x *SearchRequest) GetPolygonThreshold() float64 {
	if x != nil {
		return x.PolygonThreshold
	}
	return 0
}

func (x *SearchRequest) GetExtratags() bool {
	if x != nil {
		return x.Extratags
	}
	return false
}

func (x *SearchRequest) GetNamedetails() bool {
	if x != nil {
		return x.Namedetails
	}
	return false
}

// /search 响应
type SearchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 搜索结果列表
	Results       []*Place `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_nominatim_v1_nominatim_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nominatim_v1_nominatim_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_nominatim_v1_nominatim_proto_rawDescGZIP(), []int{7}
}

func (x *SearchResponse) GetResults() []*Place {
	if x != nil {
		return x.Results
	}
	return nil
}

// /reverse 请求
type ReverseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 纬度（范围：-90 到 90）
	Lat float64 `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	// 经度（范围：-180 到 180）
	Lon float64 `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	// 结果粒度缩放（0-30），数值越小范围越大
	Zoom uint32 `protobuf:"varint,3,opt,name=zoom,proto3" json:"zoom,omitempty"`
	// 是否返回地址行明细
	Addressdetails bool `protobuf:"varint,4,opt,name=addressdetails,proto3" json:"addressdetails,omitempty"`
	// 接受的语言（如："zh,en"），用于本地化显示
	AcceptLanguage string `protobuf:"bytes,5,opt,name=accept_language,json=acceptLanguage,proto3" json:"accept_language,omitempty"`
	// 本地化语言优先级（服务内部使用）
	Locales *Locales `protobuf:"bytes,6,opt,name=locales,proto3" json:"locales,omitempty"`
	// 是否返回多边形（GeoJSON）
	PolygonGeojson bool `protobuf:"varint,7,opt,name=polygon_geojson,json=polygonGeojson,proto3" json:"polygon_geojson,omitempty"`
	// 多边形简化阈值（0-1，越大简化越多）
	PolygonThreshold float64 `protobuf:"fixed64,8,opt,name=polygon_threshold,json=polygonThreshold,proto3" json:"polygon_threshold,omitempty"`
	// 是否返回 extratags
	Extratags bool `protobuf:"varint,9,opt,name=extratags,proto3" json:"extratags,omitempty"`
	// 是否返回 namedetails
	Namedetails   bool `protobuf:"varint,10,opt,name=namedetails,proto3" json:"namedetails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReverseRequest) Reset() {
	*x = ReverseRequest{}
	mi := &file_nominatim_v1_nominatim_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseRequest) ProtoMessage() {}

func (x *ReverseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nominatim_v1_nominatim_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseRequest.ProtoReflect.Descriptor instead.
func (*ReverseRequest) Descriptor() ([]byte, []int) {
	return file_nominatim_v1_nominatim_proto_rawDescGZIP(), []int{8}
}

func (x *ReverseRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *ReverseRequest) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *ReverseRequest) GetZoom() uint32 {
	if x != nil {
		return x.Zoom
	}
	return 0
}

func (x *ReverseRequest) GetAddressdetails() bool {
	if x != nil {
		return x.Addressdetails
	}
	return false
}

func (x *ReverseRequest) GetAcceptLanguage() string {
	if x != nil {
		return x.AcceptLanguage
	}
	return ""
}

func (x *ReverseRequest) GetLocales() *Locales {
	if x != nil {
		return x.Locales
	}
	return nil
}

func (x *ReverseRequest) GetPolygonGeojson() bool {
	if x != nil {
		return x.PolygonGeojson
	}
	return false
}

func (x *ReverseRequest) GetPolygonThreshold() float64 {
	if x != nil {
		return x.PolygonThreshold
	}
	return 0
}

func (x *ReverseRequest) GetExtratags() bool {
	if x != nil {
		return x.Extratags
	}
	return false
}

func (x *ReverseRequest) GetNamedetails() bool {
	if x != nil {
		return x.Namedetails
	}
	return false
}

// /reverse 响应
type ReverseResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 匹配到的单个地点结果
	Result        *Place `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReverseResponse) Reset() {
	*x = ReverseResponse{}
	mi := &file_nominatim_v1_nominatim_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseResponse) ProtoMessage() {}

func (x *ReverseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nominatim_v1_nominatim_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseResponse.ProtoReflect.Descriptor instead.
func (*ReverseResponse) Descriptor() ([]byte, []int) {
	return file_nominatim_v1_nominatim_proto_rawDescGZIP(), []int{9}
}

func (x *ReverseResponse) GetResult() *Place {
	if x != nil {
		return x.Result
	}
	return nil
}

// /lookup 请求
type LookupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OSM 对象 ID 列表（形如：N123、W456、R789）
	OsmIds []string `protobuf:"bytes,1,rep,name=osm_ids,json=osmIds,proto3" json:"osm_ids,omitempty"`
	// 是否返回地址行明细
	Addressdetails bool `protobuf:"varint,2,opt,name=addressdetails,proto3" json:"addressdetails,omitempty"`
	// 接受的语言（如："zh,en"），用于本地化显示
	AcceptLanguage string `protobuf:"bytes,3,opt,name=accept_language,json=acceptLanguage,proto3" json:"accept_language,omitempty"`
	// 本地化语言优先级（服务内部使用）
	Locales *Locales `protobuf:"bytes,4,opt,name=locales,proto3" json:"locales,omitempty"`
	// 是否返回 extratags
	Extratags bool `protobuf:"varint,5,opt,name=extratags,proto3" json:"extratags,omitempty"`
	// 是否返回 namedetails
	Namedetails bool `protobuf:"varint,6,opt,name=namedetails,proto3" json:"namedetails,omitempty"`
	// 是否返回多边形（GeoJSON）
	PolygonGeojson bool `protobuf:"varint,7,opt,name=polygon_geojson,json=polygonGeojson,proto3" json:"polygon_geojson,omitempty"`
	// 多边形简化阈值（0-1，越大简化越多）
	PolygonThreshold float64 `protobuf:"fixed64,8,opt,name=polygon_threshold,json=polygonThreshold,proto3" json:"polygon_threshold,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LookupRequest) Reset() {
	*x = LookupRequest{}
	mi := &file_nominatim_v1_nominatim_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupRequest) ProtoMessage() {}

func (x *LookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nominatim_v1_nominatim_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupRequest.ProtoReflect.Descriptor instead.
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return file_nominatim_v1_nominatim_proto_rawDescGZIP(), []int{10}
}

func (x *LookupRequest) GetOsmIds() []string {
	if x != nil {
		return x.OsmIds
	}
	return nil
}

func (x *LookupRequest) GetAddressdetails() bool {
	if x != nil {
		return x.Addressdetails
	}
	return false
}

func (x *LookupRequest) GetAcceptLanguage() string {
	if x != nil {
		return x.AcceptLanguage
	}
	return ""
}

func (x *LookupRequest) GetLocales() *Locales {
	if x != nil {
		return x.Locales
	}
	return nil
}

func (x *LookupRequest) GetExtratags() bool {
	if x != nil {
		return x.Extratags
	}
	return false
}

func (x *LookupRequest) GetNamedetails() bool {
	if x != nil {
		return x.Namedetails
	}
	return false
}

func (x *LookupRequest) GetPolygonGeojson() bool {
	if x != nil {
		return x.PolygonGeojson
	}
	return false
}

func (x *LookupRequest) GetPolygonThreshold() float64 {
	if x != nil {
		return x.PolygonThreshold
	}
	return 0
}

// /lookup 响应
type LookupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 查询到的对象结果列表
	Results       []*Place `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupResponse) Reset() {
	*x = LookupResponse{}
	mi := &file_nominatim_v1_nominatim_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResponse) ProtoMessage() {}

func (x *LookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nominatim_v1_nominatim_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupResponse.ProtoReflect.Descriptor instead.
func (*LookupResponse) Descriptor() ([]byte, []int) {
	return file_nominatim_v1_nominatim_proto_rawDescGZIP(), []int{11}
}

func (x *LookupResponse) GetResults() []*Place {
	if x != nil {
		return x.Results
	}
	return nil
}

// /status 请求
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_nominatim_v1_nominatim_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nominatim_v1_nominatim_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_nominatim_v1_nominatim_proto_rawDescGZIP(), []int{12}
}

// /status 响应
type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 版本号（服务与数据版本）
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// 数据库健康状态（如：ok/unavailable）
	DbStatus string `protobuf:"bytes,2,opt,name=db_status,json=dbStatus,proto3" json:"db_status,omitempty"`
	// 服务启动以来已运行时间（uptime）
	Uptime        string `protobuf:"bytes,3,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_nominatim_v1_nominatim_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nominatim_v1_nominatim_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_nominatim_v1_nominatim_proto_rawDescGZIP(), []int{13}
}

func (x *StatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StatusResponse) GetDbStatus() string {
	if x != nil {
		return x.DbStatus
	}
	return ""
}

func (x *StatusResponse) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

var File_nominatim_v1_nominatim_proto protoreflect.FileDescriptor

const file_nominatim_v1_nominatim_proto_rawDesc = "" +
	"\n" +
	"\x1cnominatim/v1/nominatim.proto\x12\fnominatim.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bbuf/validate/validate.proto\"]\n" +
	"\x05Point\x12)\n" +
	"\x03lat\x18\x01 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x80V@)\x00\x00\x00\x00\x00\x80V\xc0R\x03lat\x12)\n" +
	"\x03lon\x18\x02 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x80f@)\x00\x00\x00\x00\x00\x80f\xc0R\x03lon\"\xc1\x01\n" +
	"\aViewBox\x12+\n" +
	"\x04left\x18\x01 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x80f@)\x00\x00\x00\x00\x00\x80f\xc0R\x04left\x12)\n" +
	"\x03top\x18\x02 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x80V@)\x00\x00\x00\x00\x00\x80V\xc0R\x03top\x12-\n" +
	"\x05right\x18\x03 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x80f@)\x00\x00\x00\x00\x00\x80f\xc0R\x05right\x12/\n" +
	"\x06bottom\x18\x04 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x80V@)\x00\x00\x00\x00\x00\x80V\xc0R\x06bottom\"a\n" +
	"\vBoundingBox\x12\x14\n" +
	"\x05south\x18\x01 \x01(\x01R\x05south\x12\x14\n" +
	"\x05north\x18\x02 \x01(\x01R\x05north\x12\x12\n" +
	"\x04west\x18\x03 \x01(\x01R\x04west\x12\x12\n" +
	"\x04east\x18\x04 \x01(\x01R\x04east\"\x1f\n" +
	"\aLocales\x12\x14\n" +
	"\x05codes\x18\x01 \x03(\tR\x05codes\"{\n" +
	"\n" +
	"AddressRow\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12\x1b\n" +
	"\x04type\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04type\x12\x1f\n" +
	"\vadmin_level\x18\x03 \x01(\rR\n" +
	"adminLevel\x12\x12\n" +
	"\x04rank\x18\x04 \x01(\rR\x04rank\"\xf6\x05\n" +
	"\x05Place\x12\x19\n" +
	"\bplace_id\x18\x01 \x01(\x03R\aplaceId\x12\x18\n" +
	"\alicence\x18\x02 \x01(\tR\alicence\x12\x1e\n" +
	"\x06osm_id\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05osmId\x125\n" +
	"\bosm_type\x18\x04 \x01(\tB\x1a\xbaH\x17r\x15R\x04nodeR\x03wayR\brelationR\aosmType\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"importance\x18\a \x01(\x01R\n" +
	"importance\x12!\n" +
	"\fdisplay_name\x18\b \x01(\tR\vdisplayName\x12/\n" +
	"\bcentroid\x18\t \x01(\v2\x13.nominatim.v1.PointR\bcentroid\x12;\n" +
	"\vboundingbox\x18\n" +
	" \x01(\v2\x19.nominatim.v1.BoundingBoxR\vboundingbox\x12\x12\n" +
	"\x04icon\x18\v \x01(\tR\x04icon\x12@\n" +
	"\textratags\x18\f \x03(\v2\".nominatim.v1.Place.ExtratagsEntryR\textratags\x12F\n" +
	"\vnamedetails\x18\r \x03(\v2$.nominatim.v1.Place.NamedetailsEntryR\vnamedetails\x12;\n" +
	"\faddress_rows\x18\x0e \x03(\v2\x18.nominatim.v1.AddressRowR\vaddressRows\x12'\n" +
	"\x0fpolygon_geojson\x18\x0f \x01(\tR\x0epolygonGeojson\x1a<\n" +
	"\x0eExtratagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10NamedetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa0\x04\n" +
	"\rSearchRequest\x12\f\n" +
	"\x01q\x18\x01 \x01(\tR\x01q\x12\"\n" +
	"\fcountrycodes\x18\x02 \x01(\tR\fcountrycodes\x12\x1f\n" +
	"\x05limit\x18\x03 \x01(\rB\t\xbaH\x06*\x04\x182(\x01R\x05limit\x12\x1f\n" +
	"\x06offset\x18\x04 \x01(\rB\a\xbaH\x04*\x02(\x00R\x06offset\x12&\n" +
	"\x0eaddressdetails\x18\x05 \x01(\bR\x0eaddressdetails\x12'\n" +
	"\x0faccept_language\x18\x06 \x01(\tR\x0eacceptLanguage\x12/\n" +
	"\alocales\x18\a \x01(\v2\x15.nominatim.v1.LocalesR\alocales\x12 \n" +
	"\vfeaturetype\x18\b \x01(\tR\vfeaturetype\x12\x16\n" +
	"\x06dedupe\x18\t \x01(\bR\x06dedupe\x12/\n" +
	"\aviewbox\x18\n" +
	" \x01(\v2\x15.nominatim.v1.ViewBoxR\aviewbox\x12\x18\n" +
	"\abounded\x18\v \x01(\bR\abounded\x12'\n" +
	"\x0fpolygon_geojson\x18\f \x01(\bR\x0epolygonGeojson\x12+\n" +
	"\x11polygon_threshold\x18\r \x01(\x01R\x10polygonThreshold\x12\x1c\n" +
	"\textratags\x18\x0e \x01(\bR\textratags\x12 \n" +
	"\vnamedetails\x18\x0f \x01(\bR\vnamedetails\"?\n" +
	"\x0eSearchResponse\x12-\n" +
	"\aresults\x18\x01 \x03(\v2\x13.nominatim.v1.PlaceR\aresults\"\x9d\x03\n" +
	"\x0eReverseRequest\x12)\n" +
	"\x03lat\x18\x01 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x80V@)\x00\x00\x00\x00\x00\x80V\xc0R\x03lat\x12)\n" +
	"\x03lon\x18\x02 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x80f@)\x00\x00\x00\x00\x00\x80f\xc0R\x03lon\x12\x1d\n" +
	"\x04zoom\x18\x03 \x01(\rB\t\xbaH\x06*\x04\x18\x1e(\x00R\x04zoom\x12&\n" +
	"\x0eaddressdetails\x18\x04 \x01(\bR\x0eaddressdetails\x12'\n" +
	"\x0faccept_language\x18\x05 \x01(\tR\x0eacceptLanguage\x12/\n" +
	"\alocales\x18\x06 \x01(\v2\x15.nominatim.v1.LocalesR\alocales\x12'\n" +
	"\x0fpolygon_geojson\x18\a \x01(\bR\x0epolygonGeojson\x12+\n" +
	"\x11polygon_threshold\x18\b \x01(\x01R\x10polygonThreshold\x12\x1c\n" +
	"\textratags\x18\t \x01(\bR\textratags\x12 \n" +
	"\vnamedetails\x18\n" +
	" \x01(\bR\vnamedetails\">\n" +
	"\x0fReverseResponse\x12+\n" +
	"\x06result\x18\x01 \x01(\v2\x13.nominatim.v1.PlaceR\x06result\"\xca\x02\n" +
	"\rLookupRequest\x12!\n" +
	"\aosm_ids\x18\x01 \x03(\tB\b\xbaH\x05\x92\x01\x02\b\x01R\x06osmIds\x12&\n" +
	"\x0eaddressdetails\x18\x02 \x01(\bR\x0eaddressdetails\x12'\n" +
	"\x0faccept_language\x18\x03 \x01(\tR\x0eacceptLanguage\x12/\n" +
	"\alocales\x18\x04 \x01(\v2\x15.nominatim.v1.LocalesR\alocales\x12\x1c\n" +
	"\textratags\x18\x05 \x01(\bR\textratags\x12 \n" +
	"\vnamedetails\x18\x06 \x01(\bR\vnamedetails\x12'\n" +
	"\x0fpolygon_geojson\x18\a \x01(\bR\x0epolygonGeojson\x12+\n" +
	"\x11polygon_threshold\x18\b \x01(\x01R\x10polygonThreshold\"?\n" +
	"\x0eLookupResponse\x12-\n" +
	"\aresults\x18\x01 \x03(\v2\x13.nominatim.v1.PlaceR\aresults\"\x0f\n" +
	"\rStatusRequest\"_\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1b\n" +
	"\tdb_status\x18\x02 \x01(\tR\bdbStatus\x12\x16\n" +
	"\x06uptime\x18\x03 \x01(\tR\x06uptime2\xee\x02\n" +
	"\x10NominatimService\x12T\n" +
	"\x06Search\x12\x1b.nominatim.v1.SearchRequest\x1a\x1c.nominatim.v1.SearchResponse\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/search\x12X\n" +
	"\aReverse\x12\x1c.nominatim.v1.ReverseRequest\x1a\x1d.nominatim.v1.ReverseResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/reverse\x12T\n" +
	"\x06Lookup\x12\x1b.nominatim.v1.LookupRequest\x1a\x1c.nominatim.v1.LookupResponse\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/lookup\x12T\n" +
	"\x06Status\x12\x1b.nominatim.v1.StatusRequest\x1a\x1c.nominatim.v1.StatusResponse\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/statusB\x95\x01\n" +
	"\x10com.nominatim.v1B\x0eNominatimProtoP\x01Z nominatim-go/api/nominatim/v1;v1\xa2\x02\x03NXX\xaa\x02\fNominatim.V1\xca\x02\fNominatim\\V1\xe2\x02\x18Nominatim\\V1\\GPBMetadata\xea\x02\rNominatim::V1b\x06proto3"

var (
	file_nominatim_v1_nominatim_proto_rawDescOnce sync.Once
	file_nominatim_v1_nominatim_proto_rawDescData []byte
)

func file_nominatim_v1_nominatim_proto_rawDescGZIP() []byte {
	file_nominatim_v1_nominatim_proto_rawDescOnce.Do(func() {
		file_nominatim_v1_nominatim_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nominatim_v1_nominatim_proto_rawDesc), len(file_nominatim_v1_nominatim_proto_rawDesc)))
	})
	return file_nominatim_v1_nominatim_proto_rawDescData
}

var file_nominatim_v1_nominatim_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_nominatim_v1_nominatim_proto_goTypes = []any{
	(*Point)(nil),           // 0: nominatim.v1.Point
	(*ViewBox)(nil),         // 1: nominatim.v1.ViewBox
	(*BoundingBox)(nil),     // 2: nominatim.v1.BoundingBox
	(*Locales)(nil),         // 3: nominatim.v1.Locales
	(*AddressRow)(nil),      // 4: nominatim.v1.AddressRow
	(*Place)(nil),           // 5: nominatim.v1.Place
	(*SearchRequest)(nil),   // 6: nominatim.v1.SearchRequest
	(*SearchResponse)(nil),  // 7: nominatim.v1.SearchResponse
	(*ReverseRequest)(nil),  // 8: nominatim.v1.ReverseRequest
	(*ReverseResponse)(nil), // 9: nominatim.v1.ReverseResponse
	(*LookupRequest)(nil),   // 10: nominatim.v1.LookupRequest
	(*LookupResponse)(nil),  // 11: nominatim.v1.LookupResponse
	(*StatusRequest)(nil),   // 12: nominatim.v1.StatusRequest
	(*StatusResponse)(nil),  // 13: nominatim.v1.StatusResponse
	nil,                     // 14: nominatim.v1.Place.ExtratagsEntry
	nil,                     // 15: nominatim.v1.Place.NamedetailsEntry
}
var file_nominatim_v1_nominatim_proto_depIdxs = []int32{
	0,  // 0: nominatim.v1.Place.centroid:type_name -> nominatim.v1.Point
	2,  // 1: nominatim.v1.Place.boundingbox:type_name -> nominatim.v1.BoundingBox
	14, // 2: nominatim.v1.Place.extratags:type_name -> nominatim.v1.Place.ExtratagsEntry
	15, // 3: nominatim.v1.Place.namedetails:type_name -> nominatim.v1.Place.NamedetailsEntry
	4,  // 4: nominatim.v1.Place.address_rows:type_name -> nominatim.v1.AddressRow
	3,  // 5: nominatim.v1.SearchRequest.locales:type_name -> nominatim.v1.Locales
	1,  // 6: nominatim.v1.SearchRequest.viewbox:type_name -> nominatim.v1.ViewBox
	5,  // 7: nominatim.v1.SearchResponse.results:type_name -> nominatim.v1.Place
	3,  // 8: nominatim.v1.ReverseRequest.locales:type_name -> nominatim.v1.Locales
	5,  // 9: nominatim.v1.ReverseResponse.result:type_name -> nominatim.v1.Place
	3,  // 10: nominatim.v1.LookupRequest.locales:type_name -> nominatim.v1.Locales
	5,  // 11: nominatim.v1.LookupResponse.results:type_name -> nominatim.v1.Place
	6,  // 12: nominatim.v1.NominatimService.Search:input_type -> nominatim.v1.SearchRequest
	8,  // 13: nominatim.v1.NominatimService.Reverse:input_type -> nominatim.v1.ReverseRequest
	10, // 14: nominatim.v1.NominatimService.Lookup:input_type -> nominatim.v1.LookupRequest
	12, // 15: nominatim.v1.NominatimService.Status:input_type -> nominatim.v1.StatusRequest
	7,  // 16: nominatim.v1.NominatimService.Search:output_type -> nominatim.v1.SearchResponse
	9,  // 17: nominatim.v1.NominatimService.Reverse:output_type -> nominatim.v1.ReverseResponse
	11, // 18: nominatim.v1.NominatimService.Lookup:output_type -> nominatim.v1.LookupResponse
	13, // 19: nominatim.v1.NominatimService.Status:output_type -> nominatim.v1.StatusResponse
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_nominatim_v1_nominatim_proto_init() }
func file_nominatim_v1_nominatim_proto_init() {
	if File_nominatim_v1_nominatim_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nominatim_v1_nominatim_proto_rawDesc), len(file_nominatim_v1_nominatim_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nominatim_v1_nominatim_proto_goTypes,
		DependencyIndexes: file_nominatim_v1_nominatim_proto_depIdxs,
		MessageInfos:      file_nominatim_v1_nominatim_proto_msgTypes,
	}.Build()
	File_nominatim_v1_nominatim_proto = out.File
	file_nominatim_v1_nominatim_proto_goTypes = nil
	file_nominatim_v1_nominatim_proto_depIdxs = nil
}
