server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: postgres
    # 连接本 compose 中的 PostGIS 容器
    source: host=db user=postgres password=postgres dbname=nominatim port=5432 sslmode=disable
    debug: true
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
