// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// HelloworldsColumns holds the columns for the "helloworlds" table.
	HelloworldsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString, Default: "unknown"},
	}
	// HelloworldsTable holds the schema information for the "helloworlds" table.
	HelloworldsTable = &schema.Table{
		Name:       "helloworlds",
		Columns:    HelloworldsColumns,
		PrimaryKey: []*schema.Column{HelloworldsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		HelloworldsTable,
	}
)

func init() {
}
