// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"nominatim-go/ent/addressrow"
	"nominatim-go/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AddressRowDelete is the builder for deleting a AddressRow entity.
type AddressRowDelete struct {
	config
	hooks    []Hook
	mutation *AddressRowMutation
}

// Where appends a list predicates to the AddressRowDelete builder.
func (_d *AddressRowDelete) Where(ps ...predicate.AddressRow) *AddressRowDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AddressRowDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AddressRowDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AddressRowDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(addressrow.Table, sqlgraph.NewFieldSpec(addressrow.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AddressRowDeleteOne is the builder for deleting a single AddressRow entity.
type AddressRowDeleteOne struct {
	_d *AddressRowDelete
}

// Where appends a list predicates to the AddressRowDelete builder.
func (_d *AddressRowDeleteOne) Where(ps ...predicate.AddressRow) *AddressRowDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AddressRowDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{addressrow.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AddressRowDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
