// Code generated by ent, DO NOT EDIT.

package ent

// set all field if value is not empty. e.g. string does not equal to ""
func (_m *HelloworldCreate) SetALL(v *Helloworld) *HelloworldCreate {
	if v.Name != "" {
		_m.SetName(v.Name)
	}
	return _m
}
