// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"nominatim-go/ent/helloworld"
	"nominatim-go/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HelloworldUpdate is the builder for updating Helloworld entities.
type HelloworldUpdate struct {
	config
	hooks     []Hook
	mutation  *HelloworldMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the HelloworldUpdate builder.
func (_u *HelloworldUpdate) Where(ps ...predicate.Helloworld) *HelloworldUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *HelloworldUpdate) SetName(v string) *HelloworldUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *HelloworldUpdate) SetNillableName(v *string) *HelloworldUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// Mutation returns the HelloworldMutation object of the builder.
func (_u *HelloworldUpdate) Mutation() *HelloworldMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *HelloworldUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HelloworldUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *HelloworldUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HelloworldUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *HelloworldUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *HelloworldUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *HelloworldUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(helloworld.Table, helloworld.Columns, sqlgraph.NewFieldSpec(helloworld.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(helloworld.FieldName, field.TypeString, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{helloworld.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// HelloworldUpdateOne is the builder for updating a single Helloworld entity.
type HelloworldUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *HelloworldMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetName sets the "name" field.
func (_u *HelloworldUpdateOne) SetName(v string) *HelloworldUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *HelloworldUpdateOne) SetNillableName(v *string) *HelloworldUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// Mutation returns the HelloworldMutation object of the builder.
func (_u *HelloworldUpdateOne) Mutation() *HelloworldMutation {
	return _u.mutation
}

// Where appends a list predicates to the HelloworldUpdate builder.
func (_u *HelloworldUpdateOne) Where(ps ...predicate.Helloworld) *HelloworldUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *HelloworldUpdateOne) Select(field string, fields ...string) *HelloworldUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Helloworld entity.
func (_u *HelloworldUpdateOne) Save(ctx context.Context) (*Helloworld, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HelloworldUpdateOne) SaveX(ctx context.Context) *Helloworld {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *HelloworldUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HelloworldUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *HelloworldUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *HelloworldUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *HelloworldUpdateOne) sqlSave(ctx context.Context) (_node *Helloworld, err error) {
	_spec := sqlgraph.NewUpdateSpec(helloworld.Table, helloworld.Columns, sqlgraph.NewFieldSpec(helloworld.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Helloworld.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, helloworld.FieldID)
		for _, f := range fields {
			if !helloworld.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != helloworld.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(helloworld.FieldName, field.TypeString, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Helloworld{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{helloworld.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
