// Code generated by ent, DO NOT EDIT.

package ent

// set field if value is not empty. e.g. string does not equal to ""
func (_m *HelloworldUpdate) SetNotEmptyName(value string) *HelloworldUpdate {
	if value != "" {
		return _m.SetName(value)
	}
	return _m
}

// set field if value is not empty. e.g. string does not equal to ""
func (_m *HelloworldUpdateOne) SetNotEmptyName(value string) *HelloworldUpdateOne {
	if value != "" {
		return _m.SetName(value)
	}
	return _m
}
