// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"nominatim-go/ent/helloworld"
)

const errInvalidPage = "INVALID_PAGE"

const (
	listField     = "list"
	pageNumField  = "pageNum"
	pageSizeField = "pageSize"
)

type PageDetails struct {
	Page  uint64 `json:"page"`
	Size  uint64 `json:"size"`
	Total uint64 `json:"total"`
}

// OrderDirection defines the directions in which to order a list of items.
type OrderDirection string

const (
	// OrderDirectionAsc specifies an ascending order.
	OrderDirectionAsc OrderDirection = "ASC"
	// OrderDirectionDesc specifies a descending order.
	OrderDirectionDesc OrderDirection = "DESC"
)

// Validate the order direction value.
func (o OrderDirection) Validate() error {
	if o != OrderDirectionAsc && o != OrderDirectionDesc {
		return fmt.Errorf("%s is not a valid OrderDirection", o)
	}
	return nil
}

// String implements fmt.Stringer interface.
func (o OrderDirection) String() string {
	return string(o)
}

func (o OrderDirection) reverse() OrderDirection {
	if o == OrderDirectionDesc {
		return OrderDirectionAsc
	}
	return OrderDirectionDesc
}

const errInvalidPagination = "INVALID_PAGINATION"

type HelloworldPager struct {
	// Order OrderFunc
	Order  helloworld.OrderOption
	Filter func(*HelloworldQuery) (*HelloworldQuery, error)
}

// HelloworldPaginateOption enables pagination customization.
type HelloworldPaginateOption func(*HelloworldPager)

// DefaultHelloworldOrder is the default ordering of Helloworld.
var DefaultHelloworldOrder = Desc(helloworld.FieldID)

func newHelloworldPager(opts []HelloworldPaginateOption) (*HelloworldPager, error) {
	pager := &HelloworldPager{}
	for _, opt := range opts {
		opt(pager)
	}
	if pager.Order == nil {
		//pager.Order = DefaultHelloworldOrder
	}
	return pager, nil
}

func (p *HelloworldPager) ApplyFilter(query *HelloworldQuery) (*HelloworldQuery, error) {
	if p.Filter != nil {
		return p.Filter(query)
	}
	return query, nil
}

// HelloworldPageList is Helloworld PageList result.
type HelloworldPageList struct {
	List        []*Helloworld `json:"list"`
	PageDetails *PageDetails  `json:"pageDetails"`
}

func (_m *HelloworldQuery) Page(
	ctx context.Context, pageNum uint64, pageSize uint64, withCount bool, opts ...HelloworldPaginateOption,
) (*HelloworldPageList, error) {
	pager, err := newHelloworldPager(opts)
	if err != nil {
		return nil, err
	}

	if _m, err = pager.ApplyFilter(_m); err != nil {
		return nil, err
	}

	ret := &HelloworldPageList{}

	ret.PageDetails = &PageDetails{
		Page:  pageNum,
		Size:  pageSize,
		Total: 0,
	}

	if withCount {
		count, err := _m.Clone().Count(ctx)
		if err != nil {
			return nil, err
		}
		ret.PageDetails.Total = uint64(count)
	}

	if pager.Order != nil {
		_m = _m.Order(pager.Order)
	} else {
		//_m = _m.Order(DefaultHelloworldOrder)
	}

	_m = _m.Offset(int((pageNum - 1) * pageSize)).Limit(int(pageSize))
	list, err := _m.All(ctx)
	if err != nil {
		return nil, err
	}
	ret.List = list

	return ret, nil
}
