// Code generated by ent, DO NOT EDIT.

package ent

import (
	"nominatim-go/ent/addressrow"
	"nominatim-go/ent/helloworld"
	"nominatim-go/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	addressrowFields := schema.AddressRow{}.Fields()
	_ = addressrowFields
	// addressrowDescRank is the schema descriptor for rank field.
	addressrowDescRank := addressrowFields[4].Descriptor()
	// addressrow.DefaultRank holds the default value on creation for the rank field.
	addressrow.DefaultRank = addressrowDescRank.Default.(uint32)
	helloworldFields := schema.Helloworld{}.Fields()
	_ = helloworldFields
	// helloworldDescName is the schema descriptor for name field.
	helloworldDescName := helloworldFields[1].Descriptor()
	// helloworld.DefaultName holds the default value on creation for the name field.
	helloworld.DefaultName = helloworldDescName.Default.(string)
}
