// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Helloworld is the predicate function for helloworld builders.
type Helloworld func(*sql.Selector)
